package com.durel.bibliotheque.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Data received from the client when creating a new book.
 *
 * The book identifier and timestamps are not included because
 * they are generated by the application.
 */
public record CreateBookRequest(

        @NotBlank(message = "Title is required")
        String title,

        @NotBlank(message = "Author is required")
        String author,

        @Min(value = 1, message = "Published year must be greater than 0")
        Integer publishedYear,

        @Size(max = 100, message = "Genre must not exceed 100 characters")
        String genre,

        @Size(max = 2000, message = "Description must not exceed 2000 characters")
        String description,

        String coverUrl

) {
}